# https://school.programmers.co.kr/learn/courses/30/lessons/144853

# 풀었음
# SELECT BOOK_ID, LEFT(PUBLISHED_DATE, 10) AS PUBLISHED_DATE
# FROM BOOK
# WHERE PUBLISHED_DATE
# LIKE '2021%'
# AND CATEGORY = '인문'
# ORDER BY PUBLISHED_DATE ASC;